### ISSUE TITLE
Add support for top-level enclosed expression

### ISSUE THREAD

**Issue by lionelvillard** [lionelvillard/starlark-go#3]
For instance:

```yaml
spec:
  rules:
    { 
       for host in values.ingress.hosts:
          - host: s{ host }
    }
```
